config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :bookings, only: [:index, :create,:show]
  get 'home/index'
  post 'search/check_availbility'


  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
  belongs_to :status


  def transform
    hash_map = {
      id: self.id,
      room: self.room.name,
      room_type: self.room.room_type.name,
      start_date: self.start_date,
      end_date: self.end_date
    }
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :room_type
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  has_many :rooms
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    start_date = params[:start_date]
    end_date = params[:end_date]
    room_type = params[:room_type]
    if start_date == ''
      start_date = Date.today
    else
      start_date = Date.parse(start_date)
    end
    if end_date == ''
      end_date = start_date + 1.day
    else
      end_date = Date.parse(end_date)    
    end
    @room_types = RoomType.all
    rooms = Room.all
    if room_type != ''
      rooms = rooms.rewhere(room_type_id: room_type)
    end
    room_ids = rooms.pluck(:id)
    occupied_count = Booking.where('start_date <= ? and end_date >= ?', start_date, end_date).rewhere(status_id: 1, room_id: room_ids)
    if rooms.count > occupied_count.count
      @rooms  = rooms.where.not(id: occupied_count.pluck(:room_id))
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @room_type = params[:room_type]
    else
      @rooms = []
    end

    respond_to do |format|
      if @rooms.count > 0
        @booking = Booking.create(user: current_user, start_date: start_date, end_date:end_date, room: @rooms.first, status_id: 1)
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @room_types = RoomType.all
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def check_availbility
    start_date = params[:start_date]
    end_date = params[:end_date]
    room_type = params[:room_type]
    # binding.pry
    if start_date == ''
      start_date = Date.today
    else
      start_date = Date.parse(start_date)
    end
    if end_date == ''
      end_date = start_date + 1.day
    else
      end_date = Date.parse(end_date)    
    end
    @room_types = RoomType.all
    rooms = Room.all
    if room_type != ''
      rooms = rooms.rewhere(room_type_id: room_type)
    end
    room_ids = rooms.pluck(:id)
    occupied_count = Booking.where('start_date <= ? and end_date >= ?', start_date, end_date).rewhere(status_id: 1, room_id: room_ids)
    if rooms.count > occupied_count.count
      @rooms  = rooms.where.not(id: occupied_count.pluck(:room_id)).group(:room_type_id)
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @room_type = params[:room_type]
    else
      @rooms = []
    end

    respond_to do |format|
      format.html 
      format.json { render json: @rooms.map{|room| room.transform}}
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/application/_room_check_form.html.erb
<div class="container">
  <p>Check Room Avaiblity</p>
  <form  action="/search/check_availbility" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>


    Start Date<input type="date" name="start_date" required="true" value="<%= @start_date %>">
    End Date<input type="date" name="end_date" required="true" value="<%= @end_date %>">
    Room Type
    <select name="room_type" >
      <option value="">All</option>
      <% @room_types.each do |room_type| %>
        <option value="<%= room_type.id %>"> <%= room_type.name %></option>
      <% end %>
    </select>
    <br>
    <input type="submit" name="" value="Check  Rooms">
  </form>
</div>

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Start Date</th>

      <th>End Date</th>

      <th>Room Number</th>

    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>

        <td><%= booking.room.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<a href="/bookings">My Bookings</a>

app/views/home/index.html.erb
<%= render partial: 'room_check_form' %>




<br><br><br>
<h1>Api for search is </h1>
<p>Method Post</p>
<p>Url :  /search/check_availbility </p>
<p>
  params: 
    start_date: 'any date format '<br>
    end_date: 'any date format '<br>
    room_type : room_type_id<br>

</p>

<p>FYI i was busy with office work, didnt get much time to write clean code </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BharathHotel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/check_availbility.html.erb
<%= render partial: 'room_check_form' %>

<table>
  <thead>
    <th>
      Room Name
    </th>
    <th>
      Room Type
    </th>
  </thead>
  <tbody> 
  

  <% @rooms.each do |room| %>
      <tr>
        <td>
          <%= RoomType.find(room.room_type_id).name %>
        </td>
        <td>
          <%= form_tag('/bookings', :method => :post, :class => 'internal') %>
            <input type="hidden" name="start_date" value="<%= @start_date %>">
            <input type="hidden" name="end_date" value="<%= @end_date %>">
            <input type="hidden" name="room_type" value="<%= room.room_type_id %>">
            <input type="submit" name="" value="submit">
          </form>
        </td>
      </tr>
  <% end %>

  </tbody>